# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mb_shared_infra.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mb_shared_infra.proto',
  package='com.bt.magicbox',
  syntax='proto3',
  serialized_options=_b('\242\002\002MB'),
  serialized_pb=_b('\n\x15mb_shared_infra.proto\x12\x0f\x63om.bt.magicbox\"\x07\n\x05\x45mpty\"A\n\x1d\x46rameImageAlgProcessingResult\x12\x0f\n\x07\x66rameId\x18\x01 \x01(\r\x12\x0f\n\x07timeUtc\x18\x02 \x01(\x04\"-\n\nVector32f3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\".\n\x03Neu\x12\r\n\x05north\x18\x01 \x01(\x02\x12\x0c\n\x04\x65\x61st\x18\x02 \x01(\x02\x12\n\n\x02up\x18\x03 \x01(\x02\"-\n\nVector32s3\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"7\n\x0b\x41ttitude32f\x12\x0c\n\x04roll\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\"*\n\tSizeInt32\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\"\n\nPixelPoint\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"$\n\x08Range32f\x12\x0b\n\x03min\x18\x01 \x01(\x02\x12\x0b\n\x03max\x18\x02 \x01(\x02\"~\n\x0bGeoLocation\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x38\n\tunitsType\x18\x03 \x01(\x0e\x32%.com.bt.magicbox.GeoLocationUnitsType\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x02\"w\n\x0e\x41nchoringPoint\x12\x32\n\rpixelPosition\x18\x01 \x01(\x0b\x32\x1b.com.bt.magicbox.PixelPoint\x12\x31\n\x0bgeoPosition\x18\x02 \x01(\x0b\x32\x1c.com.bt.magicbox.GeoLocation*0\n\x14GeoLocationUnitsType\x12\x0b\n\x07\x44\x45GREES\x10\x00\x12\x0b\n\x07RADIANS\x10\x01\x42\x05\xa2\x02\x02MBb\x06proto3')
)

_GEOLOCATIONUNITSTYPE = _descriptor.EnumDescriptor(
  name='GeoLocationUnitsType',
  full_name='com.bt.magicbox.GeoLocationUnitsType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEGREES', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RADIANS', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=684,
  serialized_end=732,
)
_sym_db.RegisterEnumDescriptor(_GEOLOCATIONUNITSTYPE)

GeoLocationUnitsType = enum_type_wrapper.EnumTypeWrapper(_GEOLOCATIONUNITSTYPE)
DEGREES = 0
RADIANS = 1



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='com.bt.magicbox.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=49,
)


_FRAMEIMAGEALGPROCESSINGRESULT = _descriptor.Descriptor(
  name='FrameImageAlgProcessingResult',
  full_name='com.bt.magicbox.FrameImageAlgProcessingResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameId', full_name='com.bt.magicbox.FrameImageAlgProcessingResult.frameId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeUtc', full_name='com.bt.magicbox.FrameImageAlgProcessingResult.timeUtc', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=116,
)


_VECTOR32F3 = _descriptor.Descriptor(
  name='Vector32f3',
  full_name='com.bt.magicbox.Vector32f3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='com.bt.magicbox.Vector32f3.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='com.bt.magicbox.Vector32f3.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='com.bt.magicbox.Vector32f3.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=163,
)


_NEU = _descriptor.Descriptor(
  name='Neu',
  full_name='com.bt.magicbox.Neu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='north', full_name='com.bt.magicbox.Neu.north', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='east', full_name='com.bt.magicbox.Neu.east', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='up', full_name='com.bt.magicbox.Neu.up', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=211,
)


_VECTOR32S3 = _descriptor.Descriptor(
  name='Vector32s3',
  full_name='com.bt.magicbox.Vector32s3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='com.bt.magicbox.Vector32s3.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='com.bt.magicbox.Vector32s3.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='com.bt.magicbox.Vector32s3.z', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=258,
)


_ATTITUDE32F = _descriptor.Descriptor(
  name='Attitude32f',
  full_name='com.bt.magicbox.Attitude32f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll', full_name='com.bt.magicbox.Attitude32f.roll', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='com.bt.magicbox.Attitude32f.pitch', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='com.bt.magicbox.Attitude32f.yaw', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=315,
)


_SIZEINT32 = _descriptor.Descriptor(
  name='SizeInt32',
  full_name='com.bt.magicbox.SizeInt32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='com.bt.magicbox.SizeInt32.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='com.bt.magicbox.SizeInt32.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=359,
)


_PIXELPOINT = _descriptor.Descriptor(
  name='PixelPoint',
  full_name='com.bt.magicbox.PixelPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='com.bt.magicbox.PixelPoint.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='com.bt.magicbox.PixelPoint.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=395,
)


_RANGE32F = _descriptor.Descriptor(
  name='Range32f',
  full_name='com.bt.magicbox.Range32f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='com.bt.magicbox.Range32f.min', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='com.bt.magicbox.Range32f.max', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=433,
)


_GEOLOCATION = _descriptor.Descriptor(
  name='GeoLocation',
  full_name='com.bt.magicbox.GeoLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='com.bt.magicbox.GeoLocation.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='com.bt.magicbox.GeoLocation.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unitsType', full_name='com.bt.magicbox.GeoLocation.unitsType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='com.bt.magicbox.GeoLocation.altitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=561,
)


_ANCHORINGPOINT = _descriptor.Descriptor(
  name='AnchoringPoint',
  full_name='com.bt.magicbox.AnchoringPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pixelPosition', full_name='com.bt.magicbox.AnchoringPoint.pixelPosition', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='geoPosition', full_name='com.bt.magicbox.AnchoringPoint.geoPosition', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=682,
)

_GEOLOCATION.fields_by_name['unitsType'].enum_type = _GEOLOCATIONUNITSTYPE
_ANCHORINGPOINT.fields_by_name['pixelPosition'].message_type = _PIXELPOINT
_ANCHORINGPOINT.fields_by_name['geoPosition'].message_type = _GEOLOCATION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['FrameImageAlgProcessingResult'] = _FRAMEIMAGEALGPROCESSINGRESULT
DESCRIPTOR.message_types_by_name['Vector32f3'] = _VECTOR32F3
DESCRIPTOR.message_types_by_name['Neu'] = _NEU
DESCRIPTOR.message_types_by_name['Vector32s3'] = _VECTOR32S3
DESCRIPTOR.message_types_by_name['Attitude32f'] = _ATTITUDE32F
DESCRIPTOR.message_types_by_name['SizeInt32'] = _SIZEINT32
DESCRIPTOR.message_types_by_name['PixelPoint'] = _PIXELPOINT
DESCRIPTOR.message_types_by_name['Range32f'] = _RANGE32F
DESCRIPTOR.message_types_by_name['GeoLocation'] = _GEOLOCATION
DESCRIPTOR.message_types_by_name['AnchoringPoint'] = _ANCHORINGPOINT
DESCRIPTOR.enum_types_by_name['GeoLocationUnitsType'] = _GEOLOCATIONUNITSTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'mb_shared_infra_pb2'
  # @@protoc_insertion_point(class_scope:com.bt.magicbox.Empty)
  })
_sym_db.RegisterMessage(Empty)

FrameImageAlgProcessingResult = _reflection.GeneratedProtocolMessageType('FrameImageAlgProcessingResult', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEIMAGEALGPROCESSINGRESULT,
  '__module__' : 'mb_shared_infra_pb2'
  # @@protoc_insertion_point(class_scope:com.bt.magicbox.FrameImageAlgProcessingResult)
  })
_sym_db.RegisterMessage(FrameImageAlgProcessingResult)

Vector32f3 = _reflection.GeneratedProtocolMessageType('Vector32f3', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR32F3,
  '__module__' : 'mb_shared_infra_pb2'
  # @@protoc_insertion_point(class_scope:com.bt.magicbox.Vector32f3)
  })
_sym_db.RegisterMessage(Vector32f3)

Neu = _reflection.GeneratedProtocolMessageType('Neu', (_message.Message,), {
  'DESCRIPTOR' : _NEU,
  '__module__' : 'mb_shared_infra_pb2'
  # @@protoc_insertion_point(class_scope:com.bt.magicbox.Neu)
  })
_sym_db.RegisterMessage(Neu)

Vector32s3 = _reflection.GeneratedProtocolMessageType('Vector32s3', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR32S3,
  '__module__' : 'mb_shared_infra_pb2'
  # @@protoc_insertion_point(class_scope:com.bt.magicbox.Vector32s3)
  })
_sym_db.RegisterMessage(Vector32s3)

Attitude32f = _reflection.GeneratedProtocolMessageType('Attitude32f', (_message.Message,), {
  'DESCRIPTOR' : _ATTITUDE32F,
  '__module__' : 'mb_shared_infra_pb2'
  # @@protoc_insertion_point(class_scope:com.bt.magicbox.Attitude32f)
  })
_sym_db.RegisterMessage(Attitude32f)

SizeInt32 = _reflection.GeneratedProtocolMessageType('SizeInt32', (_message.Message,), {
  'DESCRIPTOR' : _SIZEINT32,
  '__module__' : 'mb_shared_infra_pb2'
  # @@protoc_insertion_point(class_scope:com.bt.magicbox.SizeInt32)
  })
_sym_db.RegisterMessage(SizeInt32)

PixelPoint = _reflection.GeneratedProtocolMessageType('PixelPoint', (_message.Message,), {
  'DESCRIPTOR' : _PIXELPOINT,
  '__module__' : 'mb_shared_infra_pb2'
  # @@protoc_insertion_point(class_scope:com.bt.magicbox.PixelPoint)
  })
_sym_db.RegisterMessage(PixelPoint)

Range32f = _reflection.GeneratedProtocolMessageType('Range32f', (_message.Message,), {
  'DESCRIPTOR' : _RANGE32F,
  '__module__' : 'mb_shared_infra_pb2'
  # @@protoc_insertion_point(class_scope:com.bt.magicbox.Range32f)
  })
_sym_db.RegisterMessage(Range32f)

GeoLocation = _reflection.GeneratedProtocolMessageType('GeoLocation', (_message.Message,), {
  'DESCRIPTOR' : _GEOLOCATION,
  '__module__' : 'mb_shared_infra_pb2'
  # @@protoc_insertion_point(class_scope:com.bt.magicbox.GeoLocation)
  })
_sym_db.RegisterMessage(GeoLocation)

AnchoringPoint = _reflection.GeneratedProtocolMessageType('AnchoringPoint', (_message.Message,), {
  'DESCRIPTOR' : _ANCHORINGPOINT,
  '__module__' : 'mb_shared_infra_pb2'
  # @@protoc_insertion_point(class_scope:com.bt.magicbox.AnchoringPoint)
  })
_sym_db.RegisterMessage(AnchoringPoint)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
